In [1]:
import torch

1

In [34]:
a = torch.arange(5, 8, dtype=float, requires_grad=True)
m = torch.tensor([False, True, True])
b = torch.where(m, a, torch.nan)
l = (b**2).nansum()
l.backward()
a.grad

tensor([ 0., 12., 14.], dtype=torch.float64)

In [49]:
mask

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

2

In [59]:
field = torch.randint(9, [5, 3], dtype=float, requires_grad=True)
#field = torch.rand((5,5), dtype=float, requires_grad=True)

mask = torch.ones_like(field).to(bool)
mask[:2, :5] = False

field_m = torch.where(mask, field, torch.nan)


#field.requires_grad_(True)

l = (field_m ** 2).nansum()
l.backward()
print(field.grad.sum())

tensor(224., dtype=torch.float64)


3

In [78]:
import torch.nn.functional as F 
from einops import rearrange

field = torch.randint(9, [5, 5], dtype=float, requires_grad=True)
#field = torch.rand((5,5), dtype=float, requires_grad=True)

mask = torch.ones_like(field).to(bool)
mask[:2, :3] = False

field_m = torch.where(mask, field, torch.nan)


field_inter = F.interpolate(field_m[None], size=(7), mode='linear')[0]
#field.requires_grad_(True)

l = (field_inter ** 2).nansum()
l.backward()
print(field.grad.sum())

tensor(nan, dtype=torch.float64)


# Test on interpolate

In [84]:
import torch.nn.functional as F 
from einops import rearrange

field = torch.randint(9, [5, 5], dtype=float, requires_grad=True)
#field = torch.rand((5,5), dtype=float, requires_grad=True)

mask = torch.ones_like(field).to(bool)
mask[:2, :3] = False

field_m = torch.where(mask, field, torch.nan)


field_inter = F.interpolate(field_m[None], size=(7), mode='linear')[0]
field_inter_n = torch.where(field_inter.isnan(), torch.full_like(field_inter, torch.nan), field_inter)
#field.requires_grad_(True)

l = (field_inter_n ** 2).nansum()
l.backward()
print(field.grad.sum())

tensor(170.0000, dtype=torch.float64)


In [70]:
field_inter = F.interpolate(field_m[None], size=(7), mode='linear')[0]

In [69]:
F.interpolate(a[None, None], size=(10), mode='linear')[0, 0]

tensor([0.0000, 0.2500, 0.7500, 1.2500, 1.7500, 2.2500, 2.7500,    nan,    nan,
           nan], dtype=torch.float64)

In [86]:
import torch.nn.functional as F 
from einops import rearrange

field = torch.randint(9, [5, 5], dtype=float, requires_grad=True)
#field = torch.rand((5,5), dtype=float, requires_grad=True)

mask = torch.ones_like(field).to(bool)
mask[:2, :3] = False

field_m = torch.where(mask, field, torch.nan)


field_inter = F.interpolate(field_m[None], size=(7), mode='linear')[0]
field_inter_n = torch.where(field_inter.isnan(), torch.nan, field_inter)
#field.requires_grad_(True)

l = (field_inter_n ** 2).nansum()
l.backward()
print(field.grad.sum())

tensor(199.7143, dtype=torch.float64)
